sudo: required

language: scala

jdk:
- oraclejdk8

addons:
  apt:
    packages:
    - net-tools

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

services:
  - docker

scala:
  - 2.11.8

env:
  - DOCKER_DIR="../docker/"

script:
  - export TEST_SKIP_REGEX="\[skip-tests\]"
  - if [[ (! $TRAVIS_COMMIT_MESSAGE =~ $TEST_SKIP_REGEX) || -n $TRAVIS_TAG || $TRAVIS_BRANCH == "master" ]];
      then sbt ci;
    else
      echo "Skipping tests";
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - wget https://raw.githubusercontent.com/mozilla/telemetry-batch-view/master/deploy.sh
  - export JAR="target/scala-2.11/telemetry-streaming-assembly-0.1-SNAPSHOT.jar"
  - sbt assembly

deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      repo: mozilla/telemetry-streaming
      all_branches: true
